// Code generated by "stringer -type=CaptchaType -linecomment -output captcha_string.go"; DO NOT EDIT.

package constant

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Default-1]
	_ = x[SignUp-2]
}

const _CaptchaType_name = "defaultCaptchasignupCaptcha"

var _CaptchaType_index = [...]uint8{0, 14, 27}

func (i CaptchaType) String() string {
	i -= 1
	if i < 0 || i >= CaptchaType(len(_CaptchaType_index)-1) {
		return "CaptchaType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CaptchaType_name[_CaptchaType_index[i]:_CaptchaType_index[i+1]]
}
