// Code generated by "stringer -type=HookType -linecomment -output hook_string.go"; DO NOT EDIT.

package constant

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RegisterJobs-1]
}

const _HookType_name = "registerJobs"

var _HookType_index = [...]uint8{0, 12}

func (i HookType) String() string {
	i -= 1
	if i < 0 || i >= HookType(len(_HookType_index)-1) {
		return "HookType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _HookType_name[_HookType_index[i]:_HookType_index[i+1]]
}
