// Code generated by "stringer -type=JobType -linecomment -output job_string.go"; DO NOT EDIT.

package constant

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServerStatus-1]
}

const _JobType_name = "serverStatus"

var _JobType_index = [...]uint8{0, 12}

func (i JobType) String() string {
	i -= 1
	if i < 0 || i >= JobType(len(_JobType_index)-1) {
		return "JobType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _JobType_name[_JobType_index[i]:_JobType_index[i+1]]
}
