// Code generated by "stringer -type=PermissionType -linecomment -output permission_type_string.go"; DO NOT EDIT.

package constant

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ViewRoute-1]
	_ = x[ViewMenu-2]
	_ = x[ViewResource-3]
	_ = x[ApiRoute-4]
}

const _PermissionType_name = "viewRouteviewMenuviewResourceapiRoute"

var _PermissionType_index = [...]uint8{0, 9, 17, 29, 37}

func (i PermissionType) String() string {
	i -= 1
	if i < 0 || i >= PermissionType(len(_PermissionType_index)-1) {
		return "PermissionType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PermissionType_name[_PermissionType_index[i]:_PermissionType_index[i+1]]
}
