// Code generated by "stringer -type=Prefix -linecomment -output prefix_string.go"; DO NOT EDIT.

package constant

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PermissionIdLockPrefix-1]
	_ = x[RoleIdLockPrefix-2]
}

const _Prefix_name = "lock:permissionlock:role"

var _Prefix_index = [...]uint8{0, 15, 24}

func (i Prefix) String() string {
	i -= 1
	if i < 0 || i >= Prefix(len(_Prefix_index)-1) {
		return "Prefix(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Prefix_name[_Prefix_index[i]:_Prefix_index[i+1]]
}
