// Code generated by "stringer -type=ResourceType -linecomment -output resource_type_string.go"; DO NOT EDIT.

package constant

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ViewRoute-1]
	_ = x[ViewResource-2]
	_ = x[ApiRoute-3]
}

const _ResourceType_name = "viewRouteviewResourceapiRoute"

var _ResourceType_index = [...]uint8{0, 9, 21, 29}

func (i ResourceType) String() string {
	i -= 1
	if i < 0 || i >= ResourceType(len(_ResourceType_index)-1) {
		return "ResourceType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ResourceType_name[_ResourceType_index[i]:_ResourceType_index[i+1]]
}
