// Code generated by "stringer -type=UserGender -linecomment -output user_gender_string.go"; DO NOT EDIT.

package constant

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Male-1]
	_ = x[Females-2]
}

const _UserGender_name = "malefemales"

var _UserGender_index = [...]uint8{0, 4, 11}

func (i UserGender) String() string {
	i -= 1
	if i < 0 || i >= UserGender(len(_UserGender_index)-1) {
		return "UserGender(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _UserGender_name[_UserGender_index[i]:_UserGender_index[i+1]]
}
