// Code generated by "stringer -type=UserStatus -linecomment -output user_status_string.go"; DO NOT EDIT.

package constant

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Inactive-1]
	_ = x[Normal-2]
	_ = x[Disabled-3]
}

const _UserStatus_name = "inactivenormaldisabled"

var _UserStatus_index = [...]uint8{0, 8, 14, 22}

func (i UserStatus) String() string {
	i -= 1
	if i < 0 || i >= UserStatus(len(_UserStatus_index)-1) {
		return "UserStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _UserStatus_name[_UserStatus_index[i]:_UserStatus_index[i+1]]
}
