version: "3.0"
services:
  database:
    container_name: "gin-web-database"
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "gin_web"
      MYSQL_USER: "gin_web"
      MYSQL_PASSWORD: "gin_web"
      MYSQL_ROOT_PASSWORD: "gin_web"
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
  redis:
    container_name: "gin-web-redis"
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - ./redis:/data
  minio:
    container_name: "gin-web-minio"
    restart: always
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    environment:
      MINIO_ROOT_USER: "minio_admin"
      MINIO_ROOT_PASSWORD: "minio_password"
      MINIO_REGION: "local"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API端口
      - "9001:9001"  # Web控制台端口
    expose:
      - "9000"
      - "9001"
    volumes:
      - ./minio/data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
