// Code generated by "stringer -type=cacheOperate -linecomment -output cache_operate_string.go"; DO NOT EDIT.

package cache

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[refresh-1]
	_ = x[clean-2]
}

const _cacheOperate_name = "refreshclean"

var _cacheOperate_index = [...]uint8{0, 7, 12}

func (i cacheOperate) String() string {
	i -= 1
	if i < 0 || i >= cacheOperate(len(_cacheOperate_index)-1) {
		return "cacheOperate(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _cacheOperate_name[_cacheOperate_index[i]:_cacheOperate_index[i+1]]
}
