---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Web 服务监控
  - job_name: 'weaver-service'
    static_configs:
      - targets: ['192.168.9.3:8804']
    scrape_interval: 15s
    metrics_path: '/metrics'  # 默认指标路径
    scheme: 'http'            # 使用 HTTP 协议
    # 如果需要认证，可以添加以下配置
    # basic_auth:
    #   username: 'your_username'
    #   password: 'your_password'

  # OpenTelemetry Collector 指标监控
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scheme: 'http'
    # 收集器自身指标
    relabel_configs:
      - source_labels: [__name__]
        regex: 'otelcol_.*'
        target_label: '__name__'
        replacement: 'otel_collector_${1}'

  # OpenTelemetry Collector 导出的应用指标
  - job_name: 'otel-app-metrics'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scheme: 'http'
    # 应用指标（来自OTLP）
    relabel_configs:
      - source_labels: [__name__]
        regex: 'otel_.*'
        target_label: '__name__'
        replacement: 'app_${1}'
